# Generated by Django 5.2 on 2025-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organization_admin',
            field=models.BooleanField(default=False),
        ),
    ]
